### ISSUE TITLE
update the rev for rs-srvc to v 0.13.0

### ISSUE THREAD

**Issue by tomlue** [insilica/sfac#3]
think this needs to be changed in the flake.lock. Please tell me how generating the narhash works.

**Comment by john-shaffer** [comment]
flake.lock is generated. You can pin a specific version in flake.nix by changing
```
    srvc.url = "github:insilica/rs-srvc";
```
to
```
    srvc.url = "github:insilica/rs-srvc/v0.13.0";
```
The v0.13.0 part can also be a branch or revision.
Then running any flake command will update flake.lock. `nix flake lock` will make the minimum of changes, but `nix develop` will do the trick too. `nix flake update` will pull the latest versions of everything (respecting pins).
